const paragraphs = [
  "The sun was setting on the horizon, painting the sky with a breathtaking array of oranges, pinks, and purples, while the sound of waves crashing against the shore provided a soothing background melody, and she couldn't help but feel grateful for the moment, for the beauty of nature, for the gift of life, and for the people she loved, knowing that this moment would stay with her forever.",
  "The night sky was ablaze with stars, their twinkling lights like a million fireflies in the darkness, and as she gazed up at the vast expanse of the universe above her, she was filled with a sense of wonder and amazement at the infinite possibilities and mysteries that lay beyond her reach, reminding her of her smallness in the grand scheme of things, yet also inspiring her to dream big and strive for greatness.",
  "As he sat in the hospital waiting room, surrounded by the sterile smell of disinfectant and the constant beep of machines, he couldn't help but reflect on how precious life was and how much he wanted to hold his loved ones close and cherish every moment, knowing that at any moment, everything could change and they could be gone forever.",
  "As the sun slowly rose over the mountain range, illuminating the valley below with its warm golden light, the birds began to sing their morning songs, the gentle breeze carried the sweet scent of wildflowers, and she felt at peace with herself and the world, grateful for this moment of stillness amidst the chaos of life, and she knew that she would carry this memory with her always, a reminder of the beauty and magic that surrounds us every day.",
  "In the midst of the chaos and uncertainty of the world, she held onto the hope that someday peace and love would prevail, and she worked tirelessly to spread kindness and compassion wherever she went, believing that even the smallest acts of goodness could create a ripple effect that could eventually lead to a brighter future for all humanity.",
  "With each brushstroke, the artist poured a piece of his soul onto the canvas, creating a masterpiece that would live on long after he was gone, capturing not just the beauty of the world but the emotion and depth that lay beneath its surface, a testament to the power of art to inspire and move us in ways that words could never express.",
  "The streets were crowded with people of all ages and backgrounds, their voices mingling in a cacophony of languages and dialects, the smells of exotic foods wafting through the air, and the colors of vibrant clothing and storefronts creating a feast for the eyes, as she walked through the bustling city, feeling alive and invigorated by the energy and diversity that surrounded her.",
  "The streets were filled with the hustle and bustle of people going about their day, the cacophony of honking horns and chatter blending together in a symphony of city life, but amidst the chaos she found a moment of stillness, watching as the leaves danced in the breeze and feeling a sense of peace settle over her, reminding her that even in the busiest of moments, there is always beauty to be found.",
  "The old man sat in his rocking chair on the front porch, reminiscing about his youth, when the world was simpler and the days were longer, and he longed to go back in time to relive those moments, but as he looked out at the world around him, he realized that despite all its flaws and challenges, there was still so much beauty and goodness in the world, and he felt grateful to be alive to witness it.",
];